import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'README Preview | Smart ReadmeGen',
  description: 'Professional README preview generated by AI',
  robots: 'noindex, nofollow', // Prevent indexing of preview pages
};

export default function PreviewLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen">
      {children}
    </div>
  );
}
